In [1]:
import pandas as pd
import numpy as np

In [100]:
#dfn=pd.read_csv("/data2/ffp/datasets/trainingsets/newfull/traindataset_new_norm.csv")
dfn=pd.read_csv("/mnt/nvme2tb/ffp/datasets/traindataset_new_norm.csv")
df=pd.read_csv("/mnt/nvme2tb/ffp/datasets/traindataset_new.csv")
df=df.dropna()

In [101]:
dfn

,dom_dir,dom_vel,res_max,dir_max,max_dew_temp,min_dew_temp,mean_dew_temp,max_temp,min_temp,mean_temp,...,corine_gr4,corine_gr5,corine_gr21,corine_gr22,corine_gr23,corine_gr24,corine_gr31,corine_gr32,corine_gr33,band
0,7.0,0.204624,0.204624,7.0,0.864167,0.894995,0.871111,0.657774,0.809303,0.725191,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1
1,1.0,0.290178,0.334589,8.0,0.724772,0.715282,0.711709,0.733665,0.826646,0.771734,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.767747,0.232253,0.0,1
2,7.0,0.156911,0.203335,6.0,0.735098,0.645204,0.675300,0.838963,0.783259,0.832360,...,0.0,0.0,0.341097,0.0,0.0,0.000000,0.000000,0.658903,0.0,1
3,2.0,0.067056,0.088193,7.0,0.832189,0.801324,0.798462,0.721694,0.724952,0.741619,...,0.0,0.0,0.000000,0.0,0.0,0.051634,0.000000,0.948366,0.0,1
4,7.0,0.178353,0.198610,6.0,0.786913,0.675019,0.696542,0.852739,0.782734,0.837116,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26599,2.0,0.453269,0.467147,3.0,0.771743,0.731879,0.744440,0.703920,0.840229,0.767974,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1
26600,1.0,0.414928,0.414928,1.0,0.873052,0.834348,0.841385,0.746123,0.911189,0.825115,...,0.0,0.0,0.000000,0.0,0.0,0.014181,0.202577,0.783242,0.0,1
26601,4.0,0.071755,0.076281,3.0,0.773323,0.753069,0.741789,0.685059,0.727783,0.708994,...,0.0,0.0,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0,1
26602,3.0,0.130796,0.157325,4.0,0.740828,0.707784,0.713525,0.782197,0.813289,0.790654,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1
26603,4.0,0.210528,0.210528,4.0,0.672382,0.645697,0.659924,0.570024,0.596051,0.567946,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.914035,0.085965,0.0,1

In [7]:
df.mean()

dom_vel            0.212675
res_max            1.106820
max_dew_temp       0.780956
min_dew_temp       0.726367
mean_dew_temp      0.742673
max_temp           0.749660
min_temp           0.795276
mean_temp          0.776222
rain_7_days      128.541792
ndvi               0.588334
evi                0.425765
lst_day            0.628470
lst_night          0.620076
pop                0.012250
slope              0.946384
road_dens          0.101522
dem                0.170100
aspect             0.491023
dtype: float64

In [10]:
df['rain_7_days'].min()

116.16261288841989

In [49]:
dfn[['x','y','f81','corine_gr32']]

              x         y       f81  corine_gr32
0      0.728611  0.408973  0.187007     1.000000
1      0.652766  0.519321  0.259861     0.232253
2      0.282527  0.663789  0.076102     0.658903
3      0.138324  0.655078  0.093271     0.948366
4      0.296998  0.629669  0.388399     1.000000
...         ...       ...       ...          ...
26599  0.516047  0.829311  0.373086     1.000000
26600  0.142814  0.420588  0.171694     0.783242
26601  0.255583  0.874321  0.015313     0.000000
26602  0.282527  0.668871  0.077030     1.000000
26603  0.154291  0.788657  0.048260     0.085965

[26604 rows x 4 columns]

In [102]:
dfn['dem_i'] = np.round(dfn['dem']*1000000).astype(int) 
df['dem_i'] = np.round(df['dem']*1000000).astype(int)

In [103]:
dfn['f81_i'] = np.round(dfn['f81']*1000000).astype(int) 
df['f81_i'] = np.round(df['f81']*1000000).astype(int)

In [104]:
cor_gr_cols=[c for c in dfn.columns if c.startswith('corine_gr')]
for c in cor_gr_cols:
    dfn["%s_i"%c] = np.round(dfn[c]*1000000).astype(int) 
    df["%s_i"%c] = np.round(df[c]*1000000).astype(int)

In [107]:
cor_gr_cols_i=[c for c in dfn.columns if c.startswith('corine_gr') and c.endswith('_i')]
dfj = pd.merge(dfn, df, how = 'inner', on = cor_gr_cols_i+['f81_i'])

In [108]:
dfj[['x_x','x_y','y_x','y_y','f81_x','f81_y']+["%s_x"%c for c in cor_gr_cols]+["%s_y"%c for c in cor_gr_cols]]

,x_x,x_y,y_x,y_y,f81_x,f81_y,corine_gr1_x,corine_gr4_x,corine_gr5_x,corine_gr21_x,...,corine_gr1_y,corine_gr4_y,corine_gr5_y,corine_gr21_y,corine_gr22_y,corine_gr23_y,corine_gr24_y,corine_gr31_y,corine_gr32_y,corine_gr33_y
0,0.728611,22.564470,0.408973,39.023854,0.187007,0.187007,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
1,0.728611,26.806547,0.408973,37.688862,0.187007,0.187007,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
2,0.728611,26.806547,0.408973,37.683708,0.187007,0.187007,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
3,0.728611,22.878888,0.408973,39.539294,0.187007,0.187007,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
4,0.728611,22.822190,0.408973,37.694017,0.187007,0.187007,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152287,0.599875,25.476710,0.874321,40.987683,0.072390,0.072390,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.036965,0.963035,0.0
152288,0.654762,26.043694,0.526581,38.518722,0.243619,0.243619,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0
152289,0.203190,21.378956,0.827860,40.657801,0.017169,0.017169,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.850074,0.149926,0.0
152290,0.142814,20.755273,0.420588,37.766178,0.171694,0.171694,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.014181,0.202577,0.783242,0.0
152291,0.154291,20.873824,0.788657,40.379463,0.048260,0.048260,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.914035,0.085965,0.0

In [24]:
dfj.loc[dfj['f81_i']==72390][['x_x','x_y','y_x','y_y','f81_x','f81_y']]

             x_x        x_y       y_x        y_y    f81_x    f81_y
84279   0.590894  25.383930  0.036549  35.039497  0.07239  0.07239
99622   0.658754  26.084930  0.054698  35.168357  0.07239  0.07239
111861  0.417250  23.590197  0.814066  40.559867  0.07239  0.07239
127171  0.398289  22.265514  0.862706  39.941338  0.07239  0.07239
127172  0.398289  24.275733  0.862706  35.297217  0.07239  0.07239
...          ...        ...       ...        ...      ...      ...
150170  0.127346  20.595486  0.655078  39.431052  0.07239  0.07239
150271  0.384318  23.250006  0.878677  41.018609  0.07239  0.07239
150539  0.189718  21.239787  0.795917  40.431007  0.07239  0.07239
152239  0.282527  22.198507  0.665968  39.508368  0.07239  0.07239
152287  0.599875  25.476710  0.874321  40.987683  0.07239  0.07239

[84 rows x 6 columns]

In [89]:
def xminmax(f81slice1, f81slice2, feat):
    resxmin=[]
    resxmax=[]
    for index1, row1 in f81slice1.iterrows():
        for index2, row2 in f81slice2.iterrows():
            xn1=row1['%s_x'%feat]
            xn2=row2['%s_x'%feat]
            x1=row1['%s_y'%feat]
            x2=row2['%s_y'%feat]
            if xn1==xn2:
                continue
            xmin=(xn1*x2-xn2*x1)/(xn1-xn2)
            resxmin.append(round(xmin*10**15))
            xmax=((x1-xmin+xn1*xmin)/xn1)
            resxmax.append(round(xmax*10**15))            
    return resxmin,resxmax

def filtminmax(mm1, mm2):
    xminl=set(mm1[0]).intersection(set(mm2[0]))
    xmaxl=set(mm1[1]).intersection(set(mm2[1]))
    return xminl,xmaxl

In [90]:
min1,max1=xminmax(dfj.loc[dfj['f81_i']==72390], dfj.loc[dfj['f81_i']==187007],'x')
min2,max2=xminmax(dfj.loc[dfj['f81_i']==48260], dfj.loc[dfj['f81_i']==243619],'x')
filtminmax((min1,max1),(min2,max2))

({19279996416038384, 19280000294647812},
 {29610000367839076, 29610006041613556})

In [91]:
min1,max1=xminmax(dfj.loc[dfj['f81_i']==72390], dfj.loc[dfj['f81_i']==187007],'y')
min2,max2=xminmax(dfj.loc[dfj['f81_i']==48260], dfj.loc[dfj['f81_i']==243619],'y')
filtminmax((min1,max1),(min2,max2))

({34779998076554932, 34779999225822328, 34780001703662604, 34780001964826796},
 {41879997954570680, 41880000275094904, 41880001489663408})

In [124]:
dfd=pd.read_csv('/mnt/nvme2tb/ffp/datasets/test/20190601_df.csv')

In [125]:
dfd[["x","y","x.1","y.1"]]

                x          y        x.1        y.1
0       22.770646  41.765998  22.770646  41.765998
1       22.775800  41.765998  22.775800  41.765998
2       22.780955  41.765998  22.780955  41.765998
3       22.786109  41.765998  22.786109  41.765998
4       22.791263  41.765998  22.791263  41.765998
...           ...        ...        ...        ...
649409  24.115946  34.817857  24.115946  34.817857
649410  24.110792  34.812703  24.110792  34.812703
649411  24.121100  34.812703  24.121100  34.812703
649412  24.126255  34.812703  24.126255  34.812703
649413  24.121100  34.807549  24.121100  34.807549

[649414 rows x 4 columns]

In [114]:
dfd.columns

Index(['y', 'x', 'dom_dir', 'dom_vel', 'res_max', 'dir_max', 'max_dew_temp',
       'min_dew_temp', 'mean_dew_temp', 'max_temp', 'min_temp', 'mean_temp',
       'rain_7_days', 'ndvi', 'evi', 'lst_day', 'lst_night', 'fire', 'weekday',
       'month', 'y.1', 'x.1', 'pop', 'slope', 'road_dens', 'dem', 'aspect',
       'f81', 'frequency', 'corine_13', 'corine_4', 'corine_30', 'corine_38',
       'corine_36', 'corine_10', 'corine_20', 'corine_18', 'corine_16',
       'corine_43', 'corine_27', 'corine_5', 'corine_31', 'corine_17',
       'corine_12', 'corine_26', 'corine_37', 'corine_24', 'corine_28',
       'corine_29', 'corine_19', 'corine_21', 'corine_6', 'corine_23',
       'corine_22', 'corine_1', 'corine_8', 'corine_33', 'corine_2',
       'corine_40', 'corine_32', 'corine_41', 'corine_3', 'corine_25',
       'corine_35', 'corine_14', 'corine_42', 'corine_11', 'corine_44',
       'corine_15', 'corine_7', 'corine_9', 'corine_gr1', 'corine_gr4',
       'corine_gr5', 'corine_gr21', 'corine_gr22', 'corine_gr23',
       'corine_gr24', 'corine_gr31', 'corine_gr32', 'corine_gr33', 'band'],
      dtype='object')

In [137]:
dfdn=pd.read_csv('/mnt/nvme2tb/ffp/datasets/test/20190701_df_norm.csv')

In [138]:
dfdn

,index,y,x,dom_dir,dom_vel,res_max,dir_max,max_dew_temp,min_dew_temp,mean_dew_temp,...,corine_gr4,corine_gr5,corine_gr21,corine_gr22,corine_gr23,corine_gr24,corine_gr31,corine_gr32,corine_gr33,band
0,0,0.983943,0.337913,2.0,0.067357,0.094126,1.0,0.775999,0.669359,0.696069,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
1,1,0.983943,0.338412,2.0,0.067357,0.094126,1.0,0.775999,0.669359,0.696069,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
2,2,0.983943,0.338911,2.0,0.067357,0.094126,1.0,0.775999,0.669359,0.696069,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
3,3,0.983943,0.339410,2.0,0.067357,0.094126,1.0,0.775999,0.669359,0.696069,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
4,4,0.983943,0.339909,2.0,0.067357,0.094126,1.0,0.775999,0.669359,0.696069,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654693,654693,0.005332,0.468146,0.0,0.259980,0.259980,1.0,0.809604,0.787991,0.787132,...,0.0,0.037921,0.0,0.0,0.0,0.0,0.0,0.537002,0.425077,1
654694,654694,0.004606,0.467647,0.0,0.259980,0.259980,1.0,0.809604,0.787991,0.787132,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.037931,0.962069,1
654695,654695,0.004606,0.468645,0.0,0.259980,0.259980,1.0,0.809604,0.787991,0.787132,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.008493,0.991507,1
654696,654696,0.004606,0.469144,0.0,0.259980,0.259980,1.0,0.809604,0.787991,0.787132,...,0.0,0.451182,0.0,0.0,0.0,0.0,0.0,0.000000,0.548818,1
654697,654697,0.003880,0.468645,0.0,0.259980,0.259980,1.0,0.809604,0.787991,0.787132,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.638952,0.361048,1

In [139]:
pd.DataFrame([dfdn.mean(), dfdn.min(), dfdn.max(), dfdn.std()]).transpose()

                           0             1              2              3
index          327348.500000  0.000000e+00  654697.000000  188995.177606
y                   0.666050  3.880074e-03       0.983943       0.241774
x                   0.353168  1.906875e-02       0.867325       0.174711
dom_dir             2.424150  0.000000e+00       8.000000       1.741469
dom_vel             0.166936  1.788478e-02       0.642381       0.103215
res_max             0.174850  3.332825e-02       0.642381       0.103388
dir_max             2.777809  1.000000e+00       8.000000       1.685606
max_dew_temp        0.756508  6.101744e-01       0.924704       0.056915
min_dew_temp        0.710570  5.296905e-01       0.913131       0.057229
mean_dew_temp       0.714871  5.669092e-01       0.890472       0.054932
max_temp            0.739512  6.168657e-01       0.847852       0.041592
min_temp            0.753807  5.529550e-01       0.873676       0.057978
mean_temp           0.758811  6.250295e-01       0.861406       0.041246
rain_7_days         0.012318  0.000000e+00       0.115212       0.016262
ndvi                0.688179  0.000000e+00       0.991417       0.144946
evi                 0.500105  1.184167e-01       0.934500       0.109978
lst_day             0.615696  5.532000e-01       0.674960       0.017378
lst_night           0.618268  5.497391e-01       0.651652       0.010004
fire                0.000000  0.000000e+00       0.000000       0.000000
weekday             1.000000  1.000000e+00       1.000000       0.000000
month               7.000000  7.000000e+00       7.000000       0.000000
pop                 0.012587  0.000000e+00       1.000000       0.049207
slope               0.952278  6.077348e-02       1.000000       0.064502
road_dens           0.084034  0.000000e+00       1.000000       0.100978
dem                 0.193295 -5.362325e-11       1.000000       0.157448
aspect              0.489637  0.000000e+00       1.000000       0.286172
f81                 0.092074  0.000000e+00       1.000000       0.160029
frequency           0.017800  0.000000e+00       1.000000       0.078077
corine_gr1          0.023181  0.000000e+00       1.000000       0.118995
corine_gr4          0.002491  0.000000e+00       1.000000       0.040924
corine_gr5          0.007853  0.000000e+00       1.000000       0.069350
corine_gr21         0.126482  0.000000e+00       1.000000       0.306739
corine_gr22         0.060520  0.000000e+00       1.000000       0.205720
corine_gr23         0.008128  0.000000e+00       1.000000       0.069555
corine_gr24         0.106409  0.000000e+00       1.000000       0.245744
corine_gr31         0.158491  0.000000e+00       1.000000       0.322352
corine_gr32         0.254127  0.000000e+00       1.000000       0.376987
corine_gr33         0.019013  0.000000e+00       1.000000       0.114495
band                1.000000  1.000000e+00       1.000000       0.000000

In [136]:
xn1=dfdn.iloc[678]['y']
xn2=dfdn.iloc[2039]['y']
x1=dfd.iloc[678]['y']
x2=dfd.iloc[2039]['y']
(xn1*x2-xn2*x1)/(xn1-xn2)

34.781566125615754