In [47]:
import pandas as pd

In [57]:
dfnorm=pd.read_csv('/mnt/nvme2tb/perifereia/20220902_norm.csv')

In [58]:
dfnorm.columns

Index(['index', 'Unnamed: 0', 'id', 'x', 'y', 'date', 'max_temp', 'min_temp',
       'mean_temp', 'rain_7_days', 'dom_dir', 'dom_vel', 'res_max', 'dir_max',
       'ndvi', 'evi', 'lst_night', 'lst_day', 'slope', 'curvature', 'aspect',
       'dem', 'corine_gr21', 'corine_gr22', 'corine_gr23', 'corine_gr24',
       'corine_gr31', 'corine_gr32', 'corine_gr33', 'fire', 'corine_gr1',
       'corine_gr4', 'corine_gr5', 'firedate'],
      dtype='object')

In [59]:
dfnorm

Empty DataFrame
Columns: [index, Unnamed: 0, id, x, y, date, max_temp, min_temp, mean_temp, rain_7_days, dom_dir, dom_vel, res_max, dir_max, ndvi, evi, lst_night, lst_day, slope, curvature, aspect, dem, corine_gr21, corine_gr22, corine_gr23, corine_gr24, corine_gr31, corine_gr32, corine_gr33, fire, corine_gr1, corine_gr4, corine_gr5, firedate]
Index: []

[0 rows x 34 columns]

In [53]:
dforig=pd.read_csv('/mnt/nvme2tb/perifereia/20220826.csv')

In [55]:
dforig

,Unnamed: 0,id,x,y,date,max_temp,min_temp,mean_temp,rain_7days,dom_dir,...,curvature,aspect,dem,corine_gr21,corine_gr22,corine_gr23,corine_gr24,corine_gr31,corine_gr32,corine_gr33
0,0,1,23.758767,38.254376,20220826,302.812836,293.080750,298.286346,375.630005,6,...,-3.402823e+38,-3.402823e+38,-3.402823e+38,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
1,1,2,23.759910,38.254378,20220826,302.812836,293.080750,298.286346,375.630005,6,...,-3.402823e+38,-3.402823e+38,-3.402823e+38,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
2,2,3,23.757627,38.253472,20220826,302.812836,293.080750,298.286346,375.630005,6,...,-3.402823e+38,-3.402823e+38,-3.402823e+38,0.209557,0.0,0.0,0.542136,0.000000,0.008339,0.0
3,3,4,23.758770,38.253475,20220826,302.812836,293.080750,298.286346,375.630005,6,...,-3.402823e+38,-3.402823e+38,-3.402823e+38,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
4,4,5,23.759913,38.253477,20220826,302.812836,293.080750,298.286346,375.630005,6,...,-3.402823e+38,-3.402823e+38,-3.402823e+38,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46173,46173,46026,24.010137,37.701232,20220826,301.519897,295.210754,298.830536,184.700027,2,...,-1.443598e-01,2.903057e+02,8.238805e+01,0.000000,0.0,0.0,0.169371,0.830629,0.000000,0.0
46174,46174,46027,24.011272,37.701232,20220826,301.519897,295.210754,298.830536,184.700027,2,...,6.231782e-05,2.511923e+02,9.361990e+01,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46175,46175,46028,24.012406,37.701232,20220826,301.519897,295.210754,298.830536,184.700027,2,...,8.647025e-02,2.083498e+02,1.080815e+02,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46176,46176,46029,24.013541,37.701232,20220826,301.519897,295.210754,298.830536,184.700027,2,...,2.079460e-02,1.937130e+02,1.146455e+02,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46177,46177,46030,24.014675,37.701232,20220826,301.519897,295.210754,298.830536,184.700027,2,...,9.689810e-03,1.921151e+02,1.246915e+02,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0

In [32]:
dfst=pd.read_csv('/mnt/nvme2tb/perifereia/static.csv')

In [33]:
dfst

,Unnamed: 0,id,slope,curvature,aspect,dem,x,y,corine_13,corine_4,...,corine_gr1,corine_gr4,corine_gr5,corine_gr21,corine_gr22,corine_gr23,corine_gr24,corine_gr31,corine_gr32,corine_gr33
0,0,1.0,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,23.758767,38.254376,0,0.102838,...,0.102838,0.0,0.0,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
1,1,2.0,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,23.759910,38.254378,0,0.102838,...,0.102838,0.0,0.0,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
2,2,3.0,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,23.757627,38.253472,0,0.239969,...,0.239969,0.0,0.0,0.209557,0.0,0.0,0.542136,0.000000,0.008339,0.0
3,3,4.0,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,23.758770,38.253475,0,0.102838,...,0.102838,0.0,0.0,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
4,4,5.0,-3.402823e+38,-3.402823e+38,-3.402823e+38,-3.402823e+38,23.759913,38.253477,0,0.102838,...,0.102838,0.0,0.0,0.000000,0.0,0.0,0.522939,0.000000,0.374222,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46077,46077,46026.0,4.808639e+00,-1.443598e-01,2.903057e+02,8.238805e+01,24.010137,37.701232,0,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.169371,0.830629,0.000000,0.0
46078,46078,46027.0,7.705463e+00,6.231782e-05,2.511923e+02,9.361990e+01,24.011272,37.701232,0,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46079,46079,46028.0,1.083209e+01,8.647025e-02,2.083498e+02,1.080815e+02,24.012406,37.701232,0,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46080,46080,46029.0,1.248612e+01,2.079460e-02,1.937130e+02,1.146455e+02,24.013541,37.701232,0,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0
46081,46081,46030.0,1.359031e+01,9.689810e-03,1.921151e+02,1.246915e+02,24.014675,37.701232,0,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,1.000000,0.000000,0.0